language: node_js
node_js:
  - "8"
notifications:
  email: false
before_script:
  - npm run build
script:
  - npm run test
after_success:
  - npm run doc
  - npm run report
  - npm run codecov
  - ./node_modules/.bin/codecov
deploy:
- provider: npm
  skip_cleanup: true
  email: tminier01@gmail.com
  api_key: $NPM_KEY
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs
  on:
    branch: master
