language: node_js
node_js:
  - "8"
notifications:
  email: false
script:
  - npm run test
after_success:
  - npm run coverage
  - npm run codecov
  - ./node_modules/.bin/codecov
deploy:
- provider: npm
  skip_cleanup: true
  email: tminier01@gmail.com
  api_key: $NPM_KEY
  on:
    tags: true
