language: node_js
node_js:
  - "13"
  - "12"
  - "10"
  - "8"
notifications:
  email: false
cache: yarn
script: yarn test
jobs:
  include:
    - stage: Github pages release
      script:
        - yarn build
        - yarn doc
      node_js: "12"
      deploy:
      - provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: docs
        on:
          branch: master
    - stage: npm release
      script: yarn build
      node_js: "12"
      deploy:
      - provider: npm
        skip_cleanup: true
        email: tminier01@gmail.com
        api_key: $NPM_KEY
        on:
          tags: true
