language: node_js
node_js:
  - "8"
notifications:
  email: false
cache: yarn
before_script:
  - yarn build
after_success:
  - yarn doc
deploy:
- provider: npm
  skip_cleanup: true
  email: tminier01@gmail.com
  api_key: $NPM_KEY
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs
  on:
    branch: master
